name: Sync upstream

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:

permissions:
  contents: write


jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Configure upstream remote
        run: |
          git remote get-url upstream || git remote add upstream https://github.com/nvim-telescope/telescope.nvim
      - name: Configure git user
        run: |
          git config --global user.name "un_9bot"
          git config --global user.email "un.9bot@gmail.com"
      - name: Fetch upstream and rebase
        run: |
          git fetch upstream
          git rebase upstream/master
      - name: Keep local workflows
        run: |
          git checkout origin/master -- .github/workflows
          git commit -m "Keep local workflows configuration" || echo "No workflow changes"
      - name: Push rebased master
        run: |
          git push origin master --force-with-lease
